#include "compiler_api.hpp"
#include "compiler_internal.hpp"
#include <chrono>
#include <ctime>

// CMD fails to resolve `call :label` from inside parenthesized blocks unless the call is redirected.
// Appending ` ^<nul` is a minimal no-op stdin redirect workaround (see SS64.cmd CALL notes).
static std::string appendCallNulHack(std::string batch)
{
    std::string result;
    size_t pos = 0;
    while (pos < batch.size()) {
        size_t nl = batch.find('\n', pos);
        std::string line = (nl == std::string::npos) ? batch.substr(pos) : batch.substr(pos, nl - pos);
        pos = (nl == std::string::npos) ? batch.size() : nl + 1;
        while (!line.empty() && line.back() == '\r')
            line.pop_back();
        std::string t = trim(line);
        if (startsWith(t, "call :") && !startsWith(t, "call :__main") && t.find("^<nul") == std::string::npos &&
            t.find("<nul") == std::string::npos)
            line += " ^<nul";
        result += line;
        result.push_back('\n');
    }
    return result;
}

void Compiler::emitFunction(std::ostringstream& out, const std::string& fullName, const FunctionDef& fn, const std::string& moduleName,
                            const std::string& sourceFile) {
        out << ":__fn_" << fullName << "\n";
        for (size_t i = 0; i < fn.paramDefs.size(); ++i) {
            out << "set \"" << fn.paramDefs[i].name << "=%~" << (i + 1) << "\"\n";
        }
        auto lines = transpileLines(fn.body, moduleName, nullptr, sourceFile);
        for (const auto& l : lines) {
            out << l << "\n";
        }
        out << "\n";
    }

void Compiler::emitClassMethod(std::ostringstream& out, const ClassDef& c, const FunctionDef& m, const std::string& sourceFile) {
        out << ":__class_" << c.name << "_" << m.name << "\n";
        out << "set \"__this=%~1\"\n";
        for (size_t i = 0; i < m.paramDefs.size(); ++i) {
            out << "set \"" << m.paramDefs[i].name << "=%~" << (i + 2) << "\"\n";
        }
        auto lines = transpileLines(m.body, "", nullptr, sourceFile);
        for (const auto& l : lines) {
            out << l << "\n";
        }
        out << "\n";
    }

void Compiler::emitRuntimeStdlib(std::ostringstream& out) {
        if (stdlibEmitted_) return;
        stdlibEmitted_ = true;
        out << ":__lib_arr_set\n";
        out << "set \"__arr_%~1_%~2=%~3\"\n";
        out << "exit /b 0\n\n";
        out << ":__lib_str_trim\n";
        out << "set \"_t=%~1\"\n";
        out << ":__lib_str_trim_l\n";
        out << "if \"!_t:~0,1!\"==\" \" set \"_t=!_t:~1!\"&goto __lib_str_trim_l\n";
        out << ":__lib_str_trim_t\n";
        out << "if \"!_t:~-1!\"==\" \" set \"_t=!_t:~0,-1!\"&goto __lib_str_trim_t\n";
        out << "set \"__lib_ret=!_t!\"\n";
        out << "exit /b 0\n\n";
        out << ":__lib_str_contains\n";
        out << "set \"__lib_ret=0\"\n";
        out << "if not \"%~1\"==\"%~1:%~2=%\" set \"__lib_ret=1\"\n";
        out << "exit /b 0\n\n";
        out << ":__lib_str_replace\n";
        out << "set \"_a=%~1\"\n";
        out << "set \"_f=%~2\"\n";
        out << "set \"_r=%~3\"\n";
        out << "call set \"__lib_ret=%%_a:!_f!=!_r!%%\"\n";
        out << "exit /b 0\n\n";
    }

std::string Compiler::emitBatch() {
        std::ostringstream out;
        if (debugEcho_) {
            out << "@echo on\n";
        } else {
            out << "@echo off\n";
        }
        out << "setlocal EnableExtensions EnableDelayedExpansion\n\n";
        if (emitMetadataHeader_) {
            const auto now = std::chrono::system_clock::now();
            const std::time_t nowT = std::chrono::system_clock::to_time_t(now);
            out << "rem generated by batppc\n";
            out << "rem source: " << rootInputPath_.string() << "\n";
            out << "rem version: " << compilerVersion_ << "\n";
            out << "rem timestamp: " << std::ctime(&nowT);
            out << "\n";
        }
        out << "call :__main\n";
        out << "endlocal\n";
        out << "exit /b 0\n\n";

        for (const auto& path : importOrder_) {
            const auto& p = programs_.at(path.string());
            std::string modulePrefix = p.moduleName.empty() ? "main" : p.moduleName;
            for (const auto& fn : p.functions) {
                if (fn.isMacro || fn.isInline) continue;
                std::string mangled = mangleFunctionLabel(modulePrefix, fn.name, fn.paramDefs.size());
                emitFunction(out, mangled, fn, modulePrefix, path.string());
            }
            for (const auto& c : p.classes) {
                for (const auto& f : c.fields) {
                    (void)f;
                }
                for (const auto& m : c.methods) {
                    emitClassMethod(out, c, m, path.string());
                }
            }
        }

        emitRuntimeStdlib(out);

        std::vector<std::string> mainLines;
        for (const auto& path : importOrder_) {
            const auto& p = programs_.at(path.string());
            for (const auto& e : p.enums) {
                for (size_t v = 0; v < e.variants.size(); ++v) {
                    std::string vn = trim(e.variants[v]);
                    while (!vn.empty() && (vn.back() == ',' || vn.back() == ';')) {
                        vn.pop_back();
                        vn = rtrim(vn);
                    }
                    vn = trim(vn);
                    mainLines.push_back("set \"" + e.name + "_" + vn + "=" + std::to_string(v) + "\"");
                }
            }
            auto lines = transpileLines(p.topLevelLines, p.moduleName.empty() ? "main" : p.moduleName, nullptr, path.string());
            mainLines.insert(mainLines.end(), lines.begin(), lines.end());
        }

        for (const auto& block : helperBlocks_) {
            for (const auto& l : block) {
                out << l << "\n";
            }
            out << "\n";
        }

        out << ":__main\n";
        if (!pragmaEncoding_.empty()) {
            out << "rem batpp encoding: " << pragmaEncoding_ << "\n";
        }
        for (const auto& l : mainLines) out << l << "\n";
        if (pragmaPauseOn_ && !pragmaNoPause_) {
            out << "pause\n";
        }
        out << "exit /b 0\n";
        return appendCallNulHack(out.str());
    }

std::string compileBatppFile(const fs::path& input, const CompileOptions& options) {
    Compiler c;
    return c.compileFile(input, options);
}
